[profile.default]
auto_detect_solc = true
fuzz_runs = 500
libs = ['node_modules']
optimizer = true
optimizer_runs = 500000
out = 'out'
script = 'script'
src = 'src'
solc_version = '0.8.20'
via_ir = true
fs_permissions = [
  { access = "read", path = "./node_modules/@repo/imported/files/config.json" },
  { access = "read", path = "./node_modules/@repo/imported/files" },
    { access = "read", path = "../imported/files" },
  { access = "read", path = "../imported/files/config.json" },
]